### ISSUE TITLE
Centos Support

### ISSUE THREAD

**Issue by nDiVinEx** [flyth/ts3soundbot#179]
Any information with this working on Centos?

[ts3bot@***** ts3soundboard]$ ./ts3bot
panic: unable to open database file

goroutine 1 [running]:
github.com/jmoiron/sqlx.MustExec(0x7ff09a951580, 0xc2080db9e0, 0xab0310, 0xb9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/jmoiron/sqlx/sqlx.go:669 +0xde
github.com/jmoiron/sqlx.(*DB).MustExec(0xc2080db9e0, 0xab0310, 0xb9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/jmoiron/sqlx/sqlx.go:341 +0xa2
main.main()
	/opt/go/src/frie.se/ts3bot/main.go:321 +0x1296

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [runnable]:
text/template/parse.lexText(0xc208096000, 0xaa8ef0)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208096000)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [runnable]:
database/sql.(*DB).connectionOpener(0xc2080f8140)
	/usr/local/go/src/database/sql/sql.go:588
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c
[ts3bot@***** ts3soundboard]$

**Comment by nDiVinEx** [comment]
Realised that because this is dependent on having the TS3 Client running it won't work on Centos.
