### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Samsah** [flyth/ts3soundbot#341]
Running on Debian 8. Bot uptime was around 7 days.

Started with command:
 tsbot xinit /path/to/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

What I found from screenlog:
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x32 pc=0x7f4c2e5c0c08]

runtime stack:
runtime.gothrow(0xb2dd10, 0x2a)
        /usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 398649 [syscall, locked to thread]:
runtime.cgocall_errno(0x40cbc0, 0xc20801adc8, 0x0)
        /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc20801ada8 sp=0xc20801ad80
frie.se/ts3bot/decoder._Cfunc_avdec_decode_frame(0x7f4c0c162190, 0xc200000000)
        /opt/go/src/frie.se/ts3bot/decoder/:98 +0x43 fp=0xc20801adc8 sp=0xc20801ada8
frie.se/ts3bot/decoder.(*AVDecoder).GetSamples(0xc208424eb0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:519 +0x1e8 fp=0xc20801ae48 sp=0xc20801adc8
frie.se/ts3bot/decoder.funcÂ·003()
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:577 +0x3c7 fp=0xc20801afe0 sp=0xc20801ae48
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801afe8 sp=0xc20801afe0
created by frie.se/ts3bot/decoder.(*AVDecoder).Stream
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:645 +0x372

goroutine 1 [select (no cases), 10845 minutes]:
main.main()
        /opt/go/src/frie.se/ts3bot/main.go:672 +0x2929

goroutine 5 [syscall, 10845 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.initÂ·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive, 10845 minutes]:
database/sql.(*DB).connectionOpener(0xc2080f45a0)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, 10845 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 34 [chan receive, 10845 minutes]:
database/sql.(*DB).connectionOpener(0xc20803c000)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 11 [chan receive, 10845 minutes]:
database/sql.(*DB).connectionOpener(0xc20803c320)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 13 [IO wait, 13 minutes]:
net.(*pollDesc).Wait(0xc208118c30, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208118c30, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc208118bd0, 0xc208132000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x7f4c30c22df0, 0xc208467780)
        /usr/local/go/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc2080302b0, 0xc208132000, 0x2000, 0x2000, 0xc208467720, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc2080302b0, 0xc208132000, 0x2000, 0x2000, 0xc208467720, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:82 +0x12e
main.funcÂ·140()
        /opt/go/src/frie.se/ts3bot/mode_client.go:134 +0xbc
created by main.(*BotInstance).InitMode
        /opt/go/src/frie.se/ts3bot/mode_client.go:213 +0x8fa

goroutine 14 [select, 10845 minutes]:
frie.se/ts3bot/webstream.(*WebStream).WebStream(0xc2080ab6a0)
        /opt/go/src/frie.se/ts3bot/webstream/webstream.go:171 +0x1570
created by frie.se/ts3bot/webstream.(*WebStream).Init
        /opt/go/src/frie.se/ts3bot/webstream/webstream.go:36 +0x129

goroutine 18 [IO wait, 16 minutes]:
net.(*pollDesc).Wait(0xc208118d80, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208118d80, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208118d20, 0x0, 0x7f4c30c22df0, 0xc208eda668)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208030970, 0x70ea8e, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208030970, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208064ba0, 0x7f4c30c25270, 0xc208030970, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208064ba0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20814a880, 0xc, 0x7f4c30c23010, 0xc2080f9f50, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1808 +0xba
main.ServeHTTP()
        /opt/go/src/frie.se/ts3bot/server.go:2861 +0x293a
created by main.funcÂ·036
        /opt/go/src/frie.se/ts3bot/main.go:569 +0x8c1

goroutine 16 [chan receive]:
main.funcÂ·134()
        /opt/go/src/frie.se/ts3bot/stream.go:83 +0x1fc
created by main.(*BotInstance).PlayLoop
        /opt/go/src/frie.se/ts3bot/stream.go:295 +0x1d2

goroutine 20 [chan receive, 13 minutes]:
main.funcÂ·034()
        /opt/go/src/frie.se/ts3bot/main.go:646 +0x67
created by main.funcÂ·036
        /opt/go/src/frie.se/ts3bot/main.go:653 +0x9b1

goroutine 21 [chan receive, 10845 minutes]:
main.funcÂ·035()
        /opt/go/src/frie.se/ts3bot/main.go:659 +0x64
created by main.funcÂ·036
        /opt/go/src/frie.se/ts3bot/main.go:665 +0xc1f

goroutine 66 [syscall, 10835 minutes]:
syscall.Syscall6(0x3d, 0x149b, 0xc20805a7c4, 0x0, 0xc20806e5a0, 0x0, 0x0, 0x7f4c30c11000, 0x537061, 0xc208382860)
        /usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x149b, 0xc20805a7c4, 0x0, 0xc20806e5a0, 0x90, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x149b, 0xc20805a80c, 0x0, 0xc20806e5a0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc20852e940, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc20852e940, 0xc2090f8360, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc20810a500, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:364 +0x23c
main.(*BotInstance).Spawn(0xc208102900)
        /opt/go/src/frie.se/ts3bot/mode_client.go:721 +0x5013
created by main.funcÂ·051
        /opt/go/src/frie.se/ts3bot/server.go:655 +0x2f3

goroutine 96 [select, 10834 minutes]:
frie.se/ts3bot/webstream.(*WebStream).WebStream(0xc208555b80)
        /opt/go/src/frie.se/ts3bot/webstream/webstream.go:171 +0x1570
created by frie.se/ts3bot/webstream.(*WebStream).Init
        /opt/go/src/frie.se/ts3bot/webstream/webstream.go:36 +0x129

goroutine 95 [IO wait, 16 minutes]:
net.(*pollDesc).Wait(0xc208541800, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208541800, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc2085417a0, 0xc20853a000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x7f4c30c22df0, 0xc2090f2000)
        /usr/local/go/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc208030120, 0xc20853a000, 0x2000, 0x2000, 0xc208edbe6c, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc208030120, 0xc20853a000, 0x2000, 0x2000, 0xc208edbe18, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:82 +0x12e
main.funcÂ·140()
        /opt/go/src/frie.se/ts3bot/mode_client.go:134 +0xbc
created by main.(*BotInstance).InitMode
        /opt/go/src/frie.se/ts3bot/mode_client.go:213 +0x8fa

goroutine 98 [chan receive]:
main.funcÂ·134()
        /opt/go/src/frie.se/ts3bot/stream.go:83 +0x1fc
created by main.(*BotInstance).PlayLoop
        /opt/go/src/frie.se/ts3bot/stream.go:295 +0x1d2

goroutine 182 [syscall, 10832 minutes]:
syscall.Syscall6(0x3d, 0x1535, 0xc2080577c4, 0x0, 0xc20806e630, 0x0, 0x0, 0x7f4c30c11000, 0x537061, 0xc208382b60)
        /usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x1535, 0xc2080577c4, 0x0, 0xc20806e630, 0x90, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x1535, 0xc20805780c, 0x0, 0xc20806e630, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc20854be60, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc20854be60, 0xc2090f9d10, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc20810a280, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:364 +0x23c
main.(*BotInstance).Spawn(0xc208102c00)
        /opt/go/src/frie.se/ts3bot/mode_client.go:721 +0x5013
created by main.funcÂ·051
        /opt/go/src/frie.se/ts3bot/server.go:655 +0x2f3

goroutine 398642 [syscall, locked to thread]:
frie.se/ts3bot/decoder._Cfunc_avdec_decode_frame(0x7f4c0c010430, 0x0)
        /opt/go/src/frie.se/ts3bot/decoder/:98 +0x43
frie.se/ts3bot/decoder.(*AVDecoder).GetSamples(0xc208424050, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:519 +0x1e8
frie.se/ts3bot/decoder.funcÂ·003()
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:577 +0x3c7
created by frie.se/ts3bot/decoder.(*AVDecoder).Stream
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:645 +0x372
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x32 pc=0x7f4c2e5c0c08]

runtime stack:
runtime.gothrow(0xb2dd10, 0x2a)
        /usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e
xinit: connection to X server lost


waiting for X server to shut down 
´´´

**Comment by BlueFreakLP** [comment]
Is this only happend once?

**Comment by Samsah** [comment]
So far, yes. Though, that was "first" run after setting everything up. I'll post here if it crashes again.

**Comment by Samsah** [comment]
Same thing last night.
```
2015/07/25 04:18:39 Timeout for http://stream.hive365.co.uk:8088/live retrying
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x32 pc=0x7fd4b3b49c08]

runtime stack:
runtime.gothrow(0xb2dd10, 0x2a)
        /usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 390738 [syscall, locked to thread]:
runtime.cgocall_errno(0x40cbc0, 0xc208016dc8, 0x0)
        /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208016da8 sp=0xc208016d80
frie.se/ts3bot/decoder._Cfunc_avdec_decode_frame(0x7fd48c1c9d10, 0x0)
        /opt/go/src/frie.se/ts3bot/decoder/:98 +0x43 fp=0xc208016dc8 sp=0xc208016da8
frie.se/ts3bot/decoder.(*AVDecoder).GetSamples(0xc208a16230, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:519 +0x1e8 fp=0xc208016e48 sp=0xc208016dc8
frie.se/ts3bot/decoder.funcÂ·003()
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:577 +0x3c7 fp=0xc208016fe0 sp=0xc208016e48
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208016fe8 sp=0xc208016fe0
created by frie.se/ts3bot/decoder.(*AVDecoder).Stream
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:645 +0x372

goroutine 1 [select (no cases), 12288 minutes]:
main.main()
        /opt/go/src/frie.se/ts3bot/main.go:672 +0x2929

goroutine 5 [syscall, 12288 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.initÂ·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive, 12288 minutes]:
database/sql.(*DB).connectionOpener(0xc2080f0000)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, 12288 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 23 [chan receive]:
main.funcÂ·134()
        /opt/go/src/frie.se/ts3bot/stream.go:83 +0x1fc
created by main.(*BotInstance).PlayLoop
        /opt/go/src/frie.se/ts3bot/stream.go:295 +0x1d2

goroutine 11 [chan receive, 12288 minutes]:
database/sql.(*DB).connectionOpener(0xc2080f0460)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 12 [IO wait, 9 minutes]:
net.(*pollDesc).Wait(0xc2080ec530, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080ec530, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc2080ec4d0, 0xc208126000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x7fd4b61abec0, 0xc208588910)
        /usr/local/go/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc2080300c0, 0xc208126000, 0x2000, 0x2000, 0xc2085888a0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc2080300c0, 0xc208126000, 0x2000, 0x2000, 0xc2085888a0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:82 +0x12e
main.funcÂ·140()
        /opt/go/src/frie.se/ts3bot/mode_client.go:134 +0xbc
created by main.(*BotInstance).InitMode
        /opt/go/src/frie.se/ts3bot/mode_client.go:213 +0x8fa

goroutine 13 [select, 12288 minutes]:
frie.se/ts3bot/webstream.(*WebStream).WebStream(0xc2080cb3c0)
        /opt/go/src/frie.se/ts3bot/webstream/webstream.go:171 +0x1570
created by frie.se/ts3bot/webstream.(*WebStream).Init
        /opt/go/src/frie.se/ts3bot/webstream/webstream.go:36 +0x129

goroutine 24 [chan receive]:
main.funcÂ·134()
        /opt/go/src/frie.se/ts3bot/stream.go:83 +0x1fc
created by main.(*BotInstance).PlayLoop
        /opt/go/src/frie.se/ts3bot/stream.go:295 +0x1d2

goroutine 15 [IO wait]:
net.(*pollDesc).Wait(0xc2080ec6f0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080ec6f0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc2080ec690, 0xc208128000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x7fd4b61abec0, 0xc2089a70c0)
        /usr/local/go/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc2080300e0, 0xc208128000, 0x2000, 0x2000, 0xc208030470, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc2080300e0, 0xc208128000, 0x2000, 0x2000, 0xc208030470, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:82 +0x12e
main.funcÂ·140()
        /opt/go/src/frie.se/ts3bot/mode_client.go:134 +0xbc
created by main.(*BotInstance).InitMode
        /opt/go/src/frie.se/ts3bot/mode_client.go:213 +0x8fa

goroutine 16 [select, 12288 minutes]:
frie.se/ts3bot/webstream.(*WebStream).WebStream(0xc2080cb6a0)
        /opt/go/src/frie.se/ts3bot/webstream/webstream.go:171 +0x1570
created by frie.se/ts3bot/webstream.(*WebStream).Init
        /opt/go/src/frie.se/ts3bot/webstream/webstream.go:36 +0x129

goroutine 25 [chan receive, 12287 minutes]:
database/sql.(*DB).connectionOpener(0xc2080f0dc0)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 19 [IO wait, 277 minutes]:
net.(*pollDesc).Wait(0xc2080ec7d0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080ec7d0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080ec770, 0x0, 0x7fd4b61abec0, 0xc2089af550)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208030758, 0x70ea8e, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208030758, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20805d140, 0x7fd4b61ae1d0, 0xc208030758, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20805d140, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc2080cff00, 0xc, 0x7fd4b61ac0e0, 0xc2080db350, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1808 +0xba
main.ServeHTTP()
        /opt/go/src/frie.se/ts3bot/server.go:2861 +0x293a
created by main.funcÂ·036
        /opt/go/src/frie.se/ts3bot/main.go:569 +0x8c1

goroutine 26 [syscall, 12287 minutes]:
syscall.Syscall6(0x3d, 0x33a9, 0xc208056734, 0x0, 0xc2080667e0, 0x0, 0x0, 0x7fd4b619a000, 0x537061, 0xc208282b00)
        /usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x33a9, 0xc208056734, 0x0, 0xc2080667e0, 0x90, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x33a9, 0xc20805677c, 0x0, 0xc2080667e0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc2089a9240, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc2089a9240, 0xc2089ac690, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc208068000, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:364 +0x23c
main.(*BotInstance).Spawn(0xc208100900)
        /opt/go/src/frie.se/ts3bot/mode_client.go:721 +0x5013
main.funcÂ·024()
        /opt/go/src/frie.se/ts3bot/bot.go:264 +0x1fe
created by time.goFunc
        /usr/local/go/src/time/sleep.go:129 +0x4b

goroutine 21 [chan receive, 15 minutes]:
main.funcÂ·034()
        /opt/go/src/frie.se/ts3bot/main.go:646 +0x67
created by main.funcÂ·036
        /opt/go/src/frie.se/ts3bot/main.go:653 +0x9b1

goroutine 22 [chan receive, 12288 minutes]:
main.funcÂ·035()
        /opt/go/src/frie.se/ts3bot/main.go:659 +0x64
created by main.funcÂ·036
        /opt/go/src/frie.se/ts3bot/main.go:665 +0xc1f

goroutine 249363 [chan receive]:
frie.se/ts3bot/decoder.funcÂ·003()
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:608 +0x978
created by frie.se/ts3bot/decoder.(*AVDecoder).Stream
        /opt/go/src/frie.se/ts3bot/decoder/decoder.go:645 +0x372

goroutine 249186 [syscall, 3406 minutes]:
syscall.Syscall6(0x3d, 0x4b16, 0xc2088257c4, 0x0, 0xc2080670e0, 0x0, 0x0, 0x7fd4b619a000, 0x537061, 0xc208282c80)
        /usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x4b16, 0xc2088257c4, 0x0, 0xc2080670e0, 0x90, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x4b16, 0xc20882580c, 0x0, 0xc2080670e0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc2085531c0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc2085531c0, 0xc2089c4420, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc208068280, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:364 +0x23c
main.(*BotInstance).Spawn(0xc208100c00)
        /opt/go/src/frie.se/ts3bot/mode_client.go:721 +0x5013
created by main.funcÂ·051
        /opt/go/src/frie.se/ts3bot/server.go:655 +0x2f3
xinit: connection to X server lost


waiting for X server to shut down 

´´´

**Comment by flyth** [comment]
That crash happens when the audiostream gets really corrupted. This has been fixed in a later version that has not yet been released. Thanks for reporting. :)

**Comment by Samsah** [comment]
Ok, thanks!

**Comment by BlueFreakLP** [comment]
Like Flyth said, it is fixed in future versions.
